name: Deploy React App to S3 and CloudFront

on:
  push:
    branches:
      - main # production branch
      - release/*

permissions:
  contents: read
  id-token: write # needed for OIDC

env:
  BUILD_DIR: build # change to dist for Vite

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # require approvals in GitHub
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Configure AWS credentials (via OIDC assume-role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync static assets to S3 (cacheable assets)
        run: |
          # copy hashed assets with long cache TTL
          aws s3 sync $BUILD_DIR/ s3://$S3_BUCKET_NAME/ \
            --exclude "index.html" \
            --cache-control "public, max-age=31536000, immutable" \
            --delete
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      - name: Upload index.html (short TTL)
        run: |
          aws s3 cp $BUILD_DIR/index.html s3://$S3_BUCKET_NAME/index.html \
            --cache-control "public, max-age=60, must-revalidate"
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      - name: Create CloudFront invalidation for index
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/index.html"
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
